# Generated by Django 4.0.6 on 2022-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('second_name', models.CharField(max_length=255, unique=True)),
                ('tel', models.FloatField(max_length=12)),
            ],
        ),
    ]
