# Generated by Django 4.0.6 on 2022-08-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_first_name_alter_user_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.BigIntegerField(max_length=12, unique=True),
        ),
    ]
